### PR TITLE
Fix for Ruby 2.5 compatibility.

### PR DESCRIPTION
**Pull request by junaruga**
* Created Gemfile.lock again by latest version Bundler again.  Because current `sinatra` 1.4.5 is old, and that outputs warnings.

* Updated a template file for Ruby 2.5.0 ERB syntax. Because below error was outputted.

```
$ bundle exec ./run.sh
...
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/erb.rb:885:in `eval': (erb):2: syntax error, unexpected ')', expecting end-of-input (SyntaxError)
);  user = ENV.key?("MYSQL_ROO...
```

After modification, it works.

```
$ bundle install --path vendor/bundle
$ bundle exec ./run.sh 
Run app...
[2018-02-06 19:38:04] INFO  WEBrick 1.4.2
[2018-02-06 19:38:04] INFO  ruby 2.5.0 (2017-12-25) [x86_64-linux]
== Sinatra (v2.0.0) has taken the stage on 8080 for development with backup from WEBrick
[2018-02-06 19:38:04] INFO  WEBrick::HTTPServer#start: pid=26687 port=8080
```

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by bparees** [comment]
i had to revert this because it's failing in openshift builds that clone from the repo:

```
Fetching gem metadata from https://rubygems.org/..........
Installing rake 12.3.0
Installing concurrent-ruby 1.0.5
Installing i18n 0.9.3
Installing minitest 5.11.3
Installing thread_safe 0.3.6
Installing tzinfo 1.2.5
Installing activesupport 5.1.4
Installing activemodel 5.1.4
Installing arel 8.0.0
Installing activerecord 5.1.4
Installing mustermann 1.0.1
Installing mysql2 0.4.10
Installing rack 2.0.4
Installing rack-protection 2.0.0
Installing tilt 2.0.8
Installing sinatra 2.0.0
Installing sinatra-activerecord 2.0.13
Using bundler 1.7.8
There was an error while trying to write to Gemfile.lock. It is likely that 
you need to allow write permissions for the file at path: 
/opt/app-root/src/Gemfile.lock
```

i'm not sure what the issue is yet.

**Comment by bparees** [comment]
note that the build in question is using a ruby 2.2 image, that may be part of it.

**Comment by bparees** [comment]
seems to work ok when i switch to ruby24 as the builder image.  so something about ruby22.  Going to have to make some bigger changes to get our CI switched over to use the ruby24 builder image before we can re-merge this.

**Comment by bparees** [comment]
I stood up an openshift cluster and created a buildconfig from our test fixture:
```
oc create -f ../../origin/test/extended/testdata/builds/test-docker-no-outputname.json
```

then i edited the buildconfig to point to the commit level that included your changes and ran a build.

I'm not sure why the issue isn't seen when doing a "docker build ." w/ the Dockefile in the repo, must have something to do w/ something happening during cloning but i'm quite baffled right now.

**Comment by junaruga** [comment]
@bparees About your above log, did you check the executing user's permission is ok?

```
you need to allow write permissions for the file at path: 
/opt/app-root/src/Gemfile.lock
```

**Comment by junaruga** [comment]
@bparees This PR is okay for Ruby 2.2 on my local environment.

```
$ which ruby
/usr/local/ruby-2.2.7/bin/ruby

$ ruby -v
ruby 2.2.7p470 (2017-03-28 revision 58193) [x86_64-linux]

$ bundle -v
Bundler version 1.7.8

$ which bundle
/usr/local/ruby-2.2.7/bin/bundle

$ bundle install --path vendor/bundle
Fetching gem metadata from https://rubygems.org/..........
Installing rake 12.3.0
Installing concurrent-ruby 1.0.5
Installing i18n 0.9.3
Installing minitest 5.11.3
Installing thread_safe 0.3.6
Installing tzinfo 1.2.5
Installing activesupport 5.1.4
Installing activemodel 5.1.4
Installing arel 8.0.0
Installing activerecord 5.1.4
Installing mustermann 1.0.1
Installing mysql2 0.4.10
Installing rack 2.0.4
Installing rack-protection 2.0.0
Installing tilt 2.0.8
Installing sinatra 2.0.0
Installing sinatra-activerecord 2.0.13
Using bundler 1.7.8
Your bundle is complete!
It was installed into ./vendor/bundle
```

**Comment by junaruga** [comment]
Maybe I found the reason of the issue.

After doing above process with Bundler 1.7.8, Bundler updates `Gemfile.lock`, removing `BUNDLED WITH` lines.
So, the solution is 
1. Remove the lines from `Gemfile.lock`.
or
2. Maybe your executed user permission or the directory permission is not proper. Run it with proper user.

```
$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 1715c55..7c50358 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -45,6 +45,3 @@ DEPENDENCIES
   rake
   sinatra
   sinatra-activerecord
-
-BUNDLED WITH
-   1.15.4
```

**Comment by bparees** [comment]
> Maybe your executed user permission or the directory permission is not proper. Run it with proper user.

I had tried making the Gemfile.lock world writable and it didn't fix it.  will see if your other suggestion helps.

**Pull request merged**
