### PR TITLE
Renamed runlocal.sh to run.sh

### PR DESCRIPTION
**Pull request by mfojtik**
This change allows to build and run this application using `ruby:2.1-onbuild` image.

It also picking up the `.sti/environment` file to set the RACK_ENV properly (in onbuild), since the ruby:2.1-onbuild is not setting RACK_ENV.

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees PTAL

**Comment by bparees** [comment]
that runlocal.sh assumes you've got a local mysql available, so i don't think that's quite what we want in a built in run script.  I forget, can we not just use the STI run script for the entrypoint when doing ONBUILD?

**Comment by bparees** [comment]
nm, overlooked the -z.  so i guess that's fine, but my question still stands.

**Comment by bparees** [comment]
nm x2.  forgot the point of this somewhere along the way :)

**Pull request merged**
