### PR TITLE
Update Docker build to use ruby 2.5 image

### PR DESCRIPTION
**Pull request by wewang58**
@adambkaplan @openshift/devexp-qe could you help to review it, thanks
Passed docker build with ruby 2.5 image  in local:
STEP 7: RUN scl enable rh-ruby25 "GEM_HOME=~/.gem bundle install"
Fetching gem metadata from https://rubygems.org/.........
Using rake 12.3.0
Fetching concurrent-ruby 1.1.5
Installing concurrent-ruby 1.1.5
Fetching i18n 0.9.3
Installing i18n 0.9.3
Fetching minitest 5.11.3
Installing minitest 5.11.3
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.5
Installing tzinfo 1.2.5
Fetching zeitwerk 2.2.0
Installing zeitwerk 2.2.0
Fetching activesupport 6.0.0
Installing activesupport 6.0.0
Fetching activemodel 6.0.0
Installing activemodel 6.0.0
Fetching activerecord 6.0.0
Installing activerecord 6.0.0
Using bundler 1.16.1
Fetching mustermann 1.0.3
Installing mustermann 1.0.3
Fetching mysql2 0.4.10
Installing mysql2 0.4.10 with native extensions
Fetching rack 2.0.7
Installing rack 2.0.7
Fetching rack-protection 2.0.5
Installing rack-protection 2.0.5
Fetching tilt 2.0.10
Installing tilt 2.0.10
Fetching sinatra 2.0.5
Installing sinatra 2.0.5
Fetching sinatra-activerecord 2.0.13
Installing sinatra-activerecord 2.0.13
Bundle complete! 6 Gemfile dependencies, 18 gems now installed.

### CODE REVIEW

**Comment by wewang58** [comment]
FYI, In Dockerfile I added GEM_HOME to let gem files installed to local user home directory, because default it installed in /opt/rh/rh-ruby25/root/usr/share/gems/cache/, which "default "user does not have write permission.
---in ruby 2.5----
bash-4.2$ id
uid=1001(default) gid=0(root) groups=0(root)

bash-4.2$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using rake 12.3.0
Fetching concurrent-ruby 1.1.5
Bundler::GemspecError: Could not read gem at /opt/rh/rh-ruby25/root/usr/share/gems/cache/concurrent-ruby-1.1.5.gem. It may be corrupted.
An error occurred while installing concurrent-ruby (1.1.5), and Bundler cannot continue.
Make sure that `gem install concurrent-ruby -v '1.1.5'` succeeds before bundling.
In Gemfile:
  sinatra-activerecord was resolved to 2.0.13, which depends on
    activerecord was resolved to 6.0.0, which depends on
      activemodel was resolved to 6.0.0, which depends on
        activesupport was resolved to 6.0.0, which depends on
          i18n was resolved to 0.9.3, which depends on
            concurrent-ruby

bash-4.2$ ls -al /opt/rh/rh-ruby25/root/usr/share/gems/cache/
total 8
drwxr-xr-x. 2 root root 4096 Jun  3 07:57 .
drwxr-xr-x. 8 root root 4096 Oct 10 12:07 ..

Why in ruby 2.2, bundle install success without GEM_HOME,  because gem files in default is installed in ~./gem

**Comment by adambkaplan** [comment]
@wewang58 travis is failing, a few items stand out:

1. You can update `.travis.yml` to drop the tests for ruby 2.4 and lower.
2. I suspect the library versions in `Gemfile` don't work on ruby 2.5. Update as follows:
  1. Revert your `Gemfile.lock` changes
  2. Update the library versions in `Gemfile` to more recent versions compatible with ruby 2.5
  3. Run `bundle install` locally to get the updates to `Gemfile.lock`
3. Run the test locally - `bundle exec rake test`

**Comment by wewang58** [comment]
@adambkaplan travis passed now, and dropped test for ruby 2.4 and lower versions.

**Comment by wewang58** [comment]
Found postCommit in the template: https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-dockerbuild.json#L158 need to be  consideration, so added GEM ENV to Dockerfile, so the follow builds can be all complete.
1. oc new-app openshift/ruby:2.5~xxxxxxx --strategy=docker
2. oc new-app application-template-dockerbuild.json

**Comment by adambkaplan** [comment]
@wewang58 squash your commits, then I'd say it looks good

**Comment by wewang58** [comment]
@adambkaplan commits squashed.

**Comment by adambkaplan** [comment]
/assign @bparees 

@openshift/openshift-team-developer-experience note that we may have to react to changes here in the build test suite.

**Comment by bparees** [comment]
> @openshift/openshift-team-developer-experience note that we may have to react to changes here in the build test suite.

so is it going to break CI if we merge this?  do we need to go fix up those tests in advance of these changes?

**Comment by bparees** [comment]
(what do you anticipate potentially breaking?  this should not change the behavior/output of the hello-world app, right?)

**Comment by adambkaplan** [comment]
@bparees I don't think anything _should_ break, since we are now using the ruby 2.5 imagestream tag in our build tests.

If anything we can turn on some of the start-build tests that were disabled:

https://github.com/openshift/origin/blob/master/test/extended/builds/start.go#L249
https://github.com/openshift/origin/blob/master/test/extended/builds/start.go#L272
https://github.com/openshift/origin/blob/master/test/extended/builds/start.go#L284

**Comment by adambkaplan** [comment]
@bparees tested this locally:

1. Docker image builds correctly
2. Running `scl enable rh-ruby25 "bundle exec rake test"` from the container image passes.
3. Running the container with the default commands starts the web server correctly.

looks good!

**Comment by pvalena** [comment]
This breaks our tests in [s2i-ruby-container](https://github.com/sclorg/s2i-ruby-container/issues/225), as Ruby 2.4 is still supported.

**Comment by bparees** [comment]
> This breaks our tests in s2i-ruby-container, as Ruby 2.4 is still supported.

can we create a branch for you to use with ruby 2.4?

**Comment by bparees** [comment]
(or can you fork your own copy of this repo to use in your test?)

**Comment by pvalena** [comment]
> (or can you fork your own copy of this repo to use in your test?)

We're looking into simply using an older [commit](https://github.com/sclorg/s2i-ruby-container/pull/226). So no action on your side is needed if compatibility with Ruby 2.4 is not a usecase for you.

Although I think that having a branch for Ruby 2.X compatibility would be good practice IMHO.

**Comment by pvalena** [comment]
_( I'd rather avoid duplicating the code elsewhere; and we're fine with creating PRs if the specific branch `breaks`. )_

**Pull request merged**
