### PR TITLE
Update to use Ruby 2.7

### PR DESCRIPTION
**Pull request by vrutkovs**
Ruby 2.5 is EOL in May and imagestreams for it already removed in s2i-ruby-container already

### CODE REVIEW

**Comment by junaruga** [comment]
It looks good to me!

**Comment by soltysh** [comment]
@bparees @vrutkovs this PR broke oc tests, please be more mindful next time when changing these, since they affect oc unit-tests :sweat:

**Comment by vrutkovs** [comment]
https://github.com/openshift/origin/pull/25949 should fix `oc` test. Is there any other PR required to fix oc unit tests?

**Comment by bparees** [comment]
> @bparees @vrutkovs this PR broke oc tests, please be more mindful next time when changing these, since they affect oc unit-tests

@soltysh I am sorry for the impact,  but perhaps consider defending components in the future by adding CI to this repo, if you are dependent on the the content of the repo? Or forking it into something that's more clearly a test repo?

This image is a basic "run a pod on openshift that serves content", there's really no reason for anyone to expect that merging a change into this repo would have any effect on anyone's tests as long as the image itself still builds+runs after the changes (I did confirm that prior to merging it).

**Comment by soltysh** [comment]
> @soltysh I am sorry for the impact, but perhaps consider defending components in the future by adding CI to this repo, if you are dependent on the the content of the repo? Or forking it into something that's more clearly a test repo?

Honestly, I'd prefer rewriting the units such that they don't require any external references, but that's a major task i don't have the bandwidth to deal with now :sweat:

**Comment by bparees** [comment]
> Honestly, I'd prefer rewriting the units such that they don't require any external references, but that's a major task i don't have the bandwidth to deal with now

i think forking the repo into something that's clearly a "this code is consumed by tests, don't update it unless you understand those tests" repo would go a long way to avoiding this issue in the future with pretty minimal effort.  That is more or less the same thing as not requiring external references.

@adambkaplan i think a lot of the tests that broke were build tests (see https://github.com/openshift/oc/pull/765) so you probably have a vested interest here too.

**Comment by junaruga** [comment]
I am not sure how the openshift/oc calls this repository. But simply how about using `git submodule` pinning the specific commit?

**Comment by soltysh** [comment]
> I am not sure how the openshift/oc calls this repository. But simply how about using `git submodule` pinning the specific commit?

It's possible, but honestly I'd most likely prefer unit tests not to require external deps at all, ideally.

**Pull request merged**
